accounts:
  - name: yjlee
    coins: ["100000000000000000000yasu"]
validator:
  name: yjlee
  staked: "100000000yasu"
genesis:
  chain_id: "beastheart-1"
  app_state:
    staking:
      params:
        bond_denom: "yasu"
    mint:
      params:
        mint_denom: "yasu"
    crisis:
      constant_fee:
        denom: "yasu"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "yasu"