FROM faddat/sos-lite

# Add seeds and such after doing gaia.
# I will prototype the rest of this on gaia.
RUN echo beastheart > /etc/hostname && \
		pacman -Syyu --noconfirm docker-compose zerotier-one
#		echo "docker run youngjoon-lee/beastheart" >> /usr/local/bin/firstboot.sh
# TODO: docker-compose
